package view;

import data.ServerInfo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import business.ServerService;
import view.listeners.MainWindowListener;

public class NewServerPanel extends javax.swing.JPanel {

    private MainWindowListener listener;

    public NewServerPanel(MainWindowListener listener) {
        initComponents();
        this.listener= listener; 
        registrateButtonListeners();
       
    }
  
    private void registrateButtonListeners(){
        addButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                listener.openNewServerDialog();
            }
        }); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        descriptionLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(225, 340));
        setMinimumSize(new java.awt.Dimension(225, 340));

        addButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(0, 153, 0));
        addButton.setText("+");

        descriptionLabel.setText("Add new server");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(descriptionLabel)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel descriptionLabel;
    // End of variables declaration//GEN-END:variables
}
